version: "3"

services:
  arms:
    build: ./app/
    container_name: arms
    restart: always
    ports:
      - "3000:3000"
    command: 
      "npm start"
      
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - arms
